### ISSUE TITLE
sentencepiece库出错

### ISSUE THREAD

**Issue by LHcver** [OpenGVLab/Ask-Anything#12]
主要报错是Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 

报错行： File "/opt/data/private/LH/Ask-Anything/video_miniGPT4/demo_video.py", line 58, in <module>
    model = model_cls.from_config(model_config).to('cuda:1')
  File "/opt/data/private/LH/Ask-Anything/video_miniGPT4/minigpt4/models/mini_gpt4.py", line 243, in from_config
    model = cls(
  File "/opt/data/private/LH/Ask-Anything/video_miniGPT4/minigpt4/models/mini_gpt4.py", line 86, in __init__
    self.llama_tokenizer = LlamaTokenizer.from_pretrained(llama_model, use_fast=False)  
请问是我安装的sentencepiece库出错了吗，

**Comment by Andy1621** [comment]
可以粘贴所有报错的log嘛，这个应该是安装vicuna相关环境有问题，可以参考vicuna官方README安装

**Comment by LHcver** [comment]
> 可以粘贴所有报错的log嘛，这个应该是安装vicuna相关环境有问题，可以参考vicuna官方README安装

很高兴您能及时回答  
我的报错是 
/root/anaconda3/envs/LH/lib/python3.9/site-packages/transformers/tokenization_utils_base.py:1713: FutureWarning: Calling LlamaTokenizer.from_pretrained() with the path to a single file or url is deprecated and won't be possible anymore in v5. Use a model identifier or the path to a directory instead.
  warnings.warn(
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'GPT2Tokenizer'. 
The class this function is called from is 'LlamaTokenizer'.
Traceback (most recent call last):
  File "/opt/data/private/LH/Ask-Anything/video_miniGPT4/demo_video.py", line 58, in <module>
    model = model_cls.from_config(model_config).to('cuda:1')
  File "/opt/data/private/LH/Ask-Anything/video_miniGPT4/minigpt4/models/mini_gpt4.py", line 243, in from_config
    model = cls(
  File "/opt/data/private/LH/Ask-Anything/video_miniGPT4/minigpt4/models/mini_gpt4.py", line 86, in __init__
    self.llama_tokenizer = LlamaTokenizer.from_pretrained(llama_model, use_fast=False)
  File "/root/anaconda3/envs/LH/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1811, in from_pretrained
    return cls._from_pretrained(
  File "/root/anaconda3/envs/LH/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1965, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/root/anaconda3/envs/LH/lib/python3.9/site-packages/transformers/models/llama/tokenization_llama.py", line 96, in __init__
    self.sp_model.Load(vocab_file)
  File "/root/anaconda3/envs/LH/lib/python3.9/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/root/anaconda3/envs/LH/lib/python3.9/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 
查阅相关资料应该是安装的sentencepiece库出问题了

**Comment by LHcver** [comment]
> 可以粘贴所有报错的log嘛，这个应该是安装vicuna相关环境有问题，可以参考vicuna官方README安装

会是我下载的预训练LLaMA权重有问题吗（我是从huggingface里下载（https://huggingface.co/decapoda-research/llama-13b-hf/tree/main））的

**Comment by Andy1621** [comment]
请按照[这个](https://github.com/lm-sys/FastChat/tree/v0.1.10#vicuna-weights)准备vicuana的权重
