### ISSUE TITLE
I build it on my own server, but fail to do QA when I change gpt-4 to gpt-3.5-turbo?

### ISSUE THREAD

**Issue by cocoshe** [OpenGVLab/Ask-Anything#23]
![image](https://user-images.githubusercontent.com/69197635/235354919-20266bb8-397e-474d-b4d5-fd2f6c0ed45f.png)

I just change the code here:

https://github.com/OpenGVLab/Ask-Anything/blob/d3478208dc972b32e300e9ca955dde1f4afc3013/video_chat/chatbot.py#L70

change `gpt-4` to `gpt-3.5-turbo`

And click `Run`

**Then when I try to chat with it, something wrong with langchain input param? I'm not so familiar with `langchain` way of using openai API.**

```
> Entering new AgentExecutor chain...
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 915, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/Ask-Anything/video_chat/chatbot.py", line 33, in run_text
    res = self.agent({"input": text.strip()})
  File "/root/miniconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 142, in __call__
    raise e
  File "/root/miniconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 139, in __call__
    outputs = self._call(inputs)
  File "/root/miniconda3/lib/python3.10/site-packages/langchain/agents/agent.py", line 497, in _call
    next_step_output = self._take_next_step(
  File "/root/miniconda3/lib/python3.10/site-packages/langchain/agents/agent.py", line 406, in _take_next_step
    output = self.agent.plan(intermediate_steps, **inputs)
  File "/root/miniconda3/lib/python3.10/site-packages/langchain/agents/agent.py", line 102, in plan
    action = self._get_next_action(full_inputs)
  File "/root/miniconda3/lib/python3.10/site-packages/langchain/agents/agent.py", line 63, in _get_next_action
    full_output = self.llm_chain.predict(**full_inputs)
  File "/root/miniconda3/lib/python3.10/site-packages/langchain/chains/llm.py", line 154, in predict
    return self(kwargs)[self.output_key]
  File "/root/miniconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 142, in __call__
    raise e
  File "/root/miniconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 139, in __call__
    outputs = self._call(inputs)
  File "/root/miniconda3/lib/python3.10/site-packages/langchain/chains/llm.py", line 135, in _call
    return self.apply([inputs])[0]
  File "/root/miniconda3/lib/python3.10/site-packages/langchain/chains/llm.py", line 117, in apply
    response = self.generate(input_list)
  File "/root/miniconda3/lib/python3.10/site-packages/langchain/chains/llm.py", line 59, in generate
    response = self.llm.generate(prompts, stop=stop)
  File "/root/miniconda3/lib/python3.10/site-packages/langchain/llms/base.py", line 128, in generate
    raise e
  File "/root/miniconda3/lib/python3.10/site-packages/langchain/llms/base.py", line 125, in generate
    output = self._generate(prompts, stop=stop)
  File "/root/miniconda3/lib/python3.10/site-packages/langchain/llms/openai.py", line 259, in _generate
    response = self.completion_with_retry(prompt=_prompts, **params)
  File "/root/miniconda3/lib/python3.10/site-packages/langchain/llms/openai.py", line 206, in completion_with_retry
    return _completion_with_retry(**kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/root/miniconda3/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/root/miniconda3/lib/python3.10/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/root/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/root/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/root/miniconda3/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/langchain/llms/openai.py", line 204, in _completion_with_retry
    return self.client.create(**kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/root/miniconda3/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/root/miniconda3/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/root/miniconda3/lib/python3.10/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: 'messages' is a required property
```

Any advice on solving the problem?

**Comment by cocoshe** [comment]
![image](https://user-images.githubusercontent.com/69197635/235356842-8e9f29fa-bf26-4270-9883-25fe7efdc1b7.png)

according to the openai doc, the input param should contain "messages", but the langchain must have deal with it, so strange.

**Comment by yinanhe** [comment]
What's your version of `langchian`？

**Comment by cocoshe** [comment]
> What's your version of `langchian`？

I retried the process again and worked just now:

![image](https://user-images.githubusercontent.com/69197635/235527905-13135355-9093-4ccf-8c2d-41ce068d3d58.png)

## It should be **network** problem😅

**Thanks for your reply and this interesting project~**
