### ISSUE TITLE
ModuleNotFoundError: No module named 'dataset'

### ISSUE THREAD

**Issue by qingyunyanran** [OpenGVLab/Ask-Anything#254]
Traceback (most recent call last):
  File "/home/zlj/Ask-Anything/video_chat2/tasks/train_qformer.py", line 13, in <module>
    from dataset import create_dataset, create_loader, create_sampler, Metaloader
ModuleNotFoundError: No module named 'dataset'
Traceback (most recent call last):
  File "/home/zlj/Ask-Anything/video_chat2/tasks/train_qformer.py", line 13, in <module>
    from dataset import create_dataset, create_loader, create_sampler, Metaloader
ModuleNotFoundError: No module named 'dataset'
Traceback (most recent call last):
  File "/home/zlj/Ask-Anything/video_chat2/tasks/train_qformer.py", line 13, in <module>
    from dataset import create_dataset, create_loader, create_sampler, Metaloader
ModuleNotFoundError: No module named 'dataset'
Traceback (most recent call last):
  File "/home/zlj/Ask-Anything/video_chat2/tasks/train_qformer.py", line 13, in <module>
    from dataset import create_dataset, create_loader, create_sampler, Metaloader
ModuleNotFoundError: No module named 'dataset'
Traceback (most recent call last):
  File "/home/zlj/Ask-Anything/video_chat2/tasks/train_qformer.py", line 13, in <module>
    from dataset import create_dataset, create_loader, create_sampler, Metaloader
ModuleNotFoundError: No module named 'dataset'
Traceback (most recent call last):
  File "/home/zlj/Ask-Anything/video_chat2/tasks/train_qformer.py", line 13, in <module>
    from dataset import create_dataset, create_loader, create_sampler, Metaloader
ModuleNotFoundError: No module named 'dataset'
Traceback (most recent call last):
  File "/home/zlj/Ask-Anything/video_chat2/tasks/train_qformer.py", line 13, in <module>
    from dataset import create_dataset, create_loader, create_sampler, Metaloader
ModuleNotFoundError: No module named 'dataset'
Traceback (most recent call last):
  File "/home/zlj/Ask-Anything/video_chat2/tasks/train_qformer.py", line 13, in <module>
    from dataset import create_dataset, create_loader, create_sampler, Metaloader
ModuleNotFoundError: No module named 'dataset'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1250378) of binary: /home/zlj/miniconda3/envs/videochat2/bin/python
Traceback (most recent call last):
  File "/home/zlj/miniconda3/envs/videochat2/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/zlj/miniconda3/envs/videochat2/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/zlj/miniconda3/envs/videochat2/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/zlj/miniconda3/envs/videochat2/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/zlj/miniconda3/envs/videochat2/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zlj/miniconda3/envs/videochat2/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tasks/train_qformer.py FAILED

**Comment by qingyunyanran** [comment]
Here is the error report, I don't know which part is wrong. The dataset module do exist at the correct place. But the system still mentioned "ModuleNotFoundError: No module named 'dataset'".
上面是错误报告，我不知道我到底哪里出了问题，环境完全按照指示配好了已经，dataset文件夹也在正确的位置，但是它就一直报错“ModuleNotFoundError: No module named 'dataset'”，求大佬帮帮

**Comment by yinanhe** [comment]
看起来是环境变量的问题，dataset在`video_chat2/dataset`里，需要从video_chat2文件夹启动，或者在您的PYTHONPATH中添加
```
export PYTHONPATH=your_path_to_videochat2:$PYTHONPATH
```
