### ISSUE TITLE
running problem with video_chat_with_StableLM

### ISSUE THREAD

**Issue by WaterLikely** [OpenGVLab/Ask-Anything#62]
I have installed all we need as the reference infered, when I run “python app.py”, I encoutered the problem below. I have checked the internet connection, which is OK. what's wrong with my code configuration?

Traceback (most recent call last):
  File "/data/vjuicefs_hz_cv_enhance_v1/11142060/study/Ask_anything/Ask-Anything-main/video_chat_with_StableLM/app.py", line 21, in <module>
    model = tag2text_caption(pretrained="pretrained_models/tag2text_swin_14m.pth", image_size=image_size, vit='swin_b' )
  File "/data/vjuicefs_hz_cv_enhance_v1/11142060/study/Ask_anything/Ask-Anything-main/video_chat_with_StableLM/models/tag2text.py", line 222, in tag2text_caption
    model = Tag2Text_Caption(**kwargs)
  File "/data/vjuicefs_hz_cv_enhance_v1/11142060/study/Ask_anything/Ask-Anything-main/video_chat_with_StableLM/models/tag2text.py", line 85, in __init__
    self.tokenizer = init_tokenizer()   
  File "/data/vjuicefs_hz_cv_enhance_v1/11142060/study/Ask_anything/Ask-Anything-main/video_chat_with_StableLM/models/tag2text.py", line 338, in init_tokenizer
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
  File "/opt/conda/envs/videochat/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1707, in from_pretrained
    resolved_vocab_files[file_id] = cached_path(
  File "/opt/conda/envs/videochat/lib/python3.9/site-packages/transformers/file_utils.py", line 1846, in cached_path
    output_path = get_from_cache(
  File "/opt/conda/envs/videochat/lib/python3.9/site-packages/transformers/file_utils.py", line 2102, in get_from_cache
    raise ValueError(
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

**Comment by yinanhe** [comment]
It might be because your network connection cannot connect to huggingface. Please check your network connection.
