### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!

### ISSUE THREAD

**Issue by rushzy** [OpenGVLab/Ask-Anything#68]
请问您知道这个问题应该如何解决吗？
我尝试修改Ask-Anything-main/video_miniGPT4/minigpt4/models/modeling_llama.py第74行的内容
return self.weight * hidden_states
即将self.weight和hidden_states两个变量都放在cuda:0里，但是又会在其他地方产生相同的错误

Traceback (most recent call last):
  File "home/enter/envs/minigpt4/lib/python3.9/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "home/enter/envs/minigpt4/lib/python3.9/site-packages/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "home/enter/envs/minigpt4/lib/python3.9/site-packages/gradio/blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "home/enter/envs/minigpt4/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "home/enter/envs/minigpt4/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "home/enter/envs/minigpt4/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/data/Ask-Anything-main/video_miniGPT4/demo_video.py", line 93, in gradio_answer
    llm_message = chat.answer(conv=chat_state, img_list=img_list, max_new_tokens=1000, num_beams=num_beams, temperature=temperature)[0]
  File "/data/Ask-Anything-main/video_miniGPT4/minigpt4/conversation/conversation_video.py", line 150, in answer
    outputs = self.model.llama_model.generate(
  File "home/enter/envs/minigpt4/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "home/enter/envs/minigpt4/lib/python3.9/site-packages/transformers/generation/utils.py", line 1648, in generate
    return self.sample(
  File "home/enter/envs/minigpt4/lib/python3.9/site-packages/transformers/generation/utils.py", line 2730, in sample
    outputs = self(
  File "home/enter/envs/minigpt4/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "home/enter/envs/minigpt4/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/data/Ask-Anything-main/video_miniGPT4/minigpt4/models/modeling_llama.py", line 676, in forward
    outputs = self.model(
  File "home/enter/envs/minigpt4/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/Ask-Anything-main/video_miniGPT4/minigpt4/models/modeling_llama.py", line 565, in forward
    layer_outputs = decoder_layer(
  File "home/enter/envs/minigpt4/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "home/enter/envs/minigpt4/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/data/Ask-Anything-main/video_miniGPT4/minigpt4/models/modeling_llama.py", line 272, in forward
    hidden_states = self.input_layernorm(hidden_states)
  File "home/enter/envs/minigpt4/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "home/enter/envs/minigpt4/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/data/Ask-Anything-main/video_miniGPT4/minigpt4/models/modeling_llama.py", line 74, in forward
    return self.weight * hidden_states
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!

**Comment by yinanhe** [comment]
输入的视频/图片的tensor和权重在同一张卡上吗

**Comment by yinanhe** [comment]
Due to the lack of updates for a long time, your issue has been temporarily closed. If you still have any problems, please feel free to reopen this issue.
