### ISSUE TITLE
AttributeError: 'LlamaForCausalLM' object has no attribute 'logger'

### ISSUE THREAD

**Issue by chuch1983** [OpenGVLab/Ask-Anything#87]
error log 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/peft/peft_model.py", line 288, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1265, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'PeftModelForCausalLM' object has no attribute 'logger'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/peft/tuners/lora.py", line 278, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1265, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LoraModel' object has no attribute 'logger'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xiaobingding/Ask-Anything-main/video_chat2/tasks/train_it.py", line 218, in <module>
    main(cfg)
  File "/home/xiaobingding/Ask-Anything-main/video_chat2/tasks/train_it.py", line 154, in main
    ) = setup_model(
  File "/opt/conda/lib/python3.10/site-packages/tasks/shared_utils.py", line 45, in setup_model
    model = model_cls(config=config.model)
  File "/opt/conda/lib/python3.10/site-packages/models/videochat2_it.py", line 151, in __init__
    self.llama_model.logger.info_trainable_parameters()
  File "/opt/conda/lib/python3.10/site-packages/peft/peft_model.py", line 290, in __getattr__
    return getattr(self.base_model, name)
  File "/opt/conda/lib/python3.10/site-packages/peft/tuners/lora.py", line 280, in __getattr__
    return getattr(self.model, name)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1265, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LlamaForCausalLM' object has no attribute 'logger'

torch                    1.13.0+cu117
torchvision              0.14.1+cu117

![版本](https://github.com/OpenGVLab/Ask-Anything/assets/35130001/5836c596-f683-44b0-9859-d640e0adf66b)
![报错](https://github.com/OpenGVLab/Ask-Anything/assets/35130001/d72f1e93-99dc-487f-81f4-b7a7126a02a3)

**Comment by Andy1621** [comment]
Thanks for your issue. Bug was fixed!
